apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
data:
  accesskey: {{ required "minio.accessKey is required" .Values.minio.accessKey | b64enc }}
  secretkey: {{ required "minio.secretKey is required" .Values.minio.secretKey | b64enc }}
