apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-admin
  namespace: kube-system

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: platform-admin-role
rules:
  - apiGroups: ["", "apps", "rbac.authorization.k8s.io"]
    resources: ["pods", "services", "deployments", "configmaps", "secrets", "persistentvolumeclaims", "namespaces"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: platform-admin-binding
subjects:
  - kind: ServiceAccount
    name: platform-admin
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: platform-admin-role
  apiGroup: rbac.authorization.k8s.io